scrape_configs:
  - name: "webhook demo"
    target: "pushed_payloads.json"
    metrics:
      - name: "ping_to_the_server_tcp"
        id_field: "name"
        id: "Ping to the server (TCP)"
        value_field: "value"
        description: "ping to the server tcp"
      - name: "ping_to_the_server_percentage_packet_loss"
        id_field: "name"
        id: "Ping to the server Percentage Packet Loss"
        value_field: "value"
        description: "percent package loss"
      - name: "ping_to_the_server_response_time"
        id_field: "name"
        id: "Ping to the server Response Time"
        value_field: "value"
        description: "percent package loss"
    labels:
      - name: "host.host"
        rename: "host"
      - name: "clock"
        rename: "timestamp"